import os
SQLALCHEMY_DATABASE_URI = "sqlite:///db.sqlite"
#SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL')
#DATABASE_URL
SQLALCHEMY_TRACK_MODIFICATIONS = False

#SECRET_KEY = os.getenv('SECRET_KEY')
SECRET_KEY = "abcdefg123456"

WTF_CSRF_ENABLED = True
FLASK_ADMIN_SWATCH = 'cosmo'

OPENAPI_URL_PREFIX = '/api/swagger'
OPENAPI_SWAGGER_UI_PATH = '/'
OPENAPI_SWAGGER_UI_VERSION = '3.22.0'
